name: Linux-fixedDataTable-longOutput
on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run every 2 hours.
    - cron:  '0 */2 * * *'
jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    env:
      BROWSERS: '["chromium"]'
      PLAYWRIGTH: ${{ matrix.PLAYWRIGTH }}
      JLAB_HOME: '/home/runner/work/benchmarks/jupyterlab'
      JLAB_REPO: "https://github.com/jupyterlab/jupyterlab.git"
      # BENCHMARKS
      BENCHMARK_NOTEBOOKS: '["./fixedDataTable", "./longOutput"]'
      BENCHMARK_MAX_N: ${{ matrix.BENCHMARK_MAX_N }}
      BENCHMARK_NUMBER_SAMPLES: ${{ matrix.BENCHMARK_NUMBER_SAMPLES }}
      BENCHMARK_SWITCHES: ${{ matrix.BENCHMARK_SWITCHES }}
      BENCHMARK_MAX_TIME: ${{ matrix.BENCHMARK_MAX_TIME }}
      BENCHMARK_OUTPUT: ${{ matrix.PLAYWRIGTH }}-fixedDataTable-longOutput-${{ matrix.TABLE_ROWS }}-${{ matrix.TABLE_COLUMNS }}-${{ matrix.DIV_NUMBER }}.csv
      # fixedDataTable.ts
      TABLE_ROWS: ${{ matrix.TABLE_ROWS }}
      TABLE_COLUMNS: ${{ matrix.TABLE_COLUMNS }}
      # longOutputs.ts
      DIV_NUMBER: ${{ matrix.DIV_NUMBER }}
    strategy:
      matrix:
        PYTHON: [3.8]
        NODEJS: [12.x]
        PLAYWRIGTH: ['1.0.2', '1.3.0']
        # JupyterLab [older-commit]
        JLAB_COMMITS: [1f15fcb]  # Replace by branch
        # Benchmarks
        BENCHMARK_MAX_N: [100]          # Default is 100
        BENCHMARK_NUMBER_SAMPLES: [21]  # Default is 20
        BENCHMARK_SWITCHES: [10]
        BENCHMARK_MAX_TIME: [20000]     # Default is 5000
        # fixedDataTable.ts
        TABLE_ROWS: [5000]              # Default is 5000
        TABLE_COLUMNS: [50]             # Default is 50
        # longOutputs.ts
        DIV_NUMBER: [100]               # Default is 100
      fail-fast: false
    timeout-minutes: 60
    steps:
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.PYTHON }}
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.NODEJS }}
      - name: Checkout benchmarks repository
        uses: actions/checkout@v2
      - name: Install JupyterLab
        run: |
          cd ..
          git clone $JLAB_REPO
          cd jupyterlab
          git checkout ${{ matrix.JLAB_COMMITS }}
          cd ..
          python benchmarks/packages/compare/patch_package_json.py
          cd jupyterlab
          pip install plotly==4.5.4 ipywidgets==7.5.1
          pip install -e .
          jlpm install
          jlpm run build
      - name: Install playwright action
        uses: microsoft/playwright-github-action@v1
      - name: Install benchmarks
        run: |
          python packages/compare/patch_playwright.py
          jlpm
      - name: List python dependencies
        run: pip list
      - name: List npm dependencies
        continue-on-error: true
        run: npm list --silent
      - name: List JLab dev_mode dependencies
        continue-on-error: true
        run: |
          cd ..
          cd jupyterlab/dev_mode
          npm list --silent
      - name: Run benchmarks
        uses: GabrielBB/xvfb-action@v1.2
        with:
          run: jlpm ci
      - name: Remove notebook checkpoints and copy to artifacts folder
        run: |
          rm -rf notebooks/.ipynb_checkpoints/
      - name: Upload benchmark csv and notebook data artifacts
        uses: actions/upload-artifact@v2
        with:
          name: benchmarks
          path: |
            *.csv
            *.json
            notebooks/
            !analysis.vl.json
            !comparison.vl.json
            !package.json
            !tsconfig.json

  linux-compare:
    name: Linux
    runs-on: ubuntu-latest
    needs: linux
    env:
      OLD_KEY: '1.0.2'
      NEW_KEY: '1.3.0'
      KEY_TYPE: playwright
    strategy:
      matrix:
        PYTHON: [3.8]
        NODEJS: [12.x]
      fail-fast: false
    timeout-minutes: 10
    steps:
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.PYTHON }}
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.NODEJS }}
      - name: Checkout benchmarks repository
        uses: actions/checkout@v2
      - name: Install compare tools
        run: |
          cd packages/compare
          npm install
      - name: List python dependencies
        run: pip list
      - name: List npm dependencies
        continue-on-error: true
        run: npm list --silent
      - name: Download the benchmark data from previous jobs
        uses: actions/download-artifact@v2
        with:
          name: benchmarks
          path: packages/compare
      - name: Check
        run: |
          cd packages/compare
          ls
      - name: Run compare python script
        run: |
          cd packages/compare
          python compare.py
      - uses: actions/upload-artifact@v2
        with:
          name: results
          path: |
            packages/compare/*.csv
            packages/compare/*.json
            packages/compare/*.vl.json
            packages/compare/notebooks/*.ipynb
            !packages/compare/package.json
            !packages/compare/package-lock.json
            !packages/compare/tsconfig.json
